### ISSUE TITLE
Implement Admin Dashboard

### ISSUE THREAD

**Issue by timzprof** [DSC-Unilag/DSC-Blog#21]
- Mockup: https://xd.adobe.com/spec/95e42f88-1f12-4b4e-4e88-b792f040a020-e3d5/

**Comment by geektutor** [comment]
@AbdussamadYisau work on page 6 of the mockup. Please drop a comment here when done

**Comment by AbdussamadYisau** [comment]
@geektutor Okay, no problem.

**Comment by geektutor** [comment]
@FavourOyewumi7 work on page 2 and 3 of the mockup. Drop a comment here when done

https://xd.adobe.com/spec/95e42f88-1f12-4b4e-4e88-b792f040a020-e3d5/

**Comment by geektutor** [comment]
@Seriking work on page 4 and 5 of the mockup. Drop a comment here when done

https://xd.adobe.com/spec/95e42f88-1f12-4b4e-4e88-b792f040a020-e3d5/

**Comment by AbdussamadYisau** [comment]
> @AbdussamadYisau work on page 6 of the mockup. Please drop a comment here when done

Done

**Comment by timzprof** [comment]
@FavourOyewumi7 @Seriking How far?

**Comment by FavourOyewumi7** [comment]
please what is the password to the xd something oh, it is asking for
password
